function x = displacement(sho, t_end, opt)
    arguments
        sho DampedOscillator
        t_end (1,1) double {mustBeNonnegative} = 1.0
        opt.TimeResolution (1,1) double {mustBePositive} = 0.1
        opt.InitialPosition (1,1) double = 1.0
        opt.InitialVelocity (1,1) double = 0.0
    end

    damping_type = query_damping_type(sho);
    if isequal(damping_type, "underdamping")
        x = sho.displacement_for_underdamping_case(t_end, ...
            TimeResolution = opt.TimeResolution, ...
            InitialPosition = opt.InitialPosition, ...
            InitialVelocity = opt.InitialVelocity);
    elseif isequal(damping_type, "overdamping")
        x = sho.displacement_for_overdamping_case(t_end, ...
            TimeResolution = opt.TimeResolution, ...
            InitialPosition = opt.InitialPosition, ...
            InitialVelocity = opt.InitialVelocity);
    else
        x = sho.displacement_for_critical_damping_case(t_end, ...
            TimeResolution = opt.TimeResolution, ...
            InitialPosition = opt.InitialPosition, ...
            InitialVelocity = opt.InitialVelocity);
    end
end
